# -*- coding: utf-8 -*-
"""coco8_train_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ywp44xL5-HpsrLIWKIdnzywUgnMK7NO6

## 安裝環境
"""

# 安裝 YOLOv8 和 下載工具 FiftyOne
!pip install ultralytics fiftyone

"""## 下載並篩選 COCO 資料 (只抓 8 類)"""

import fiftyone as fo
import fiftyone.zoo as foz
import os

# 1. 設定類別 (COCO 標準名稱)
classes = ["spoon", "banana", "keyboard", "cell phone", "book", "scissors", "bottle", "cup"]

print("🚀 開始下載並篩選圖片... (請耐心等待 3-5 分鐘)")

# 2. 下載資料
# 我們從 'train' split 中抓取，設定 max_samples 限制總張數，避免下載太久
dataset = foz.load_zoo_dataset(
    "coco-2017",
    split="train",
    label_types=["detections"],
    classes=classes,
    max_samples=3000,  # 抓 3000 張來測試就好，太少沒效果，太多跑太久
    only_matching=True,
    shuffle=True,      # 隨機抓取，確保類別平均
    seed=42
)

# 3. 匯出成 YOLOv8 格式
export_dir = "/content/coco_subset_224"
label_field = "ground_truth"

if os.path.exists(export_dir):
    import shutil
    shutil.rmtree(export_dir) # 清除舊資料

dataset.export(
    export_dir=export_dir,
    dataset_type=fo.types.YOLOv5Dataset, # YOLOv8 通用格式
    label_field=label_field,
    classes=classes,
)

print(f"✅ 資料準備完成！儲存於: {export_dir}")

"""## 建立設定檔 (data.yaml)"""

import os
import shutil

# 定義根目錄
base_dir = '/content/coco_subset_224'

# 1. 檢查並修復 images 資料夾
if os.path.exists(f"{base_dir}/images/val") and not os.path.exists(f"{base_dir}/images/train"):
    print("發現 images/val，正在改名為 images/train ...")
    shutil.move(f"{base_dir}/images/val", f"{base_dir}/images/train")
    print("✅ images 資料夾修復完成")

# 2. 檢查並修復 labels 資料夾
if os.path.exists(f"{base_dir}/labels/val") and not os.path.exists(f"{base_dir}/labels/train"):
    print("發現 labels/val，正在改名為 labels/train ...")
    shutil.move(f"{base_dir}/labels/val", f"{base_dir}/labels/train")
    print("✅ labels 資料夾修復完成")

# 再次確認
if os.path.exists(f"{base_dir}/images/train"):
    print(f"現在目錄結構正確: {os.listdir(f'{base_dir}/images')}")
else:
    print("⚠️ 警告: 還是沒看到 train 資料夾，請確認資料是否下載成功")

import yaml
from ultralytics import YOLO

# 1. 重新寫入正確的 dataset.yaml
data_config = {
    'path': '/content/coco_subset_224',
    'train': 'images/train',  # 改好名的資料夾
    'val': 'images/train',    # 暫時讓驗證集也讀取同一份資料，避免報錯
    'nc': 8,
    'names': {
        0: 'spoon',
        1: 'banana',
        2: 'keyboard',
        3: 'cell phone',
        4: 'book',
        5: 'scissors',
        6: 'bottle',
        7: 'cup'
    }
}

with open('/content/coco_subset_224/dataset.yaml', 'w') as f:
    yaml.dump(data_config, f)

print("✅ dataset.yaml 更新完成")

"""## 開始訓練 (Training)"""

from ultralytics import YOLO

# 1. 載入預訓練模型
model = YOLO('yolov8n.pt')

# 2. 開始訓練
# imgsz=224: 為了速度 (配合你的作業要求)
# epochs=100: 測試跑多久
# batch=64: 因為圖片很小，Batch 可以開大一點，加速訓練
results = model.train(
    data='/content/coco_subset_224/dataset.yaml',
    epochs=100,
    imgsz=224,
    batch=64,
    name='yolov8n_224_coco_test'
)